=== Inadequado4192/UkrainianPlease/Translations/Scheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="TranslationDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="originalMod">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="id" type="xs:string" />
                            <xs:element name="packageId" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="li" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nickname" type="xs:string" />
                                        <xs:element name="steamId" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- Додаємо опціональний елемент SourceTranslationId -->
                <xs:element name="sourceTranslationId" type="xs:string" minOccurs="0" />

                <xs:element name="lastUpdate" type="xs:dateTime" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Achtung/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Inadequado4192/UkrainianPlease/master/Translations/Scheme.xsd">
    <originalMod>
        <name>Achtung!</name>
        <id>730936602</id>
        <packageId>brrainz.achtung</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>AntiJaoi</nickname>
            <steamId>76561198066973088</steamId>
        </li>
    </authors>
    <sourceTranslationId>2942230958</sourceTranslationId>
    <lastUpdate>2023-03-12T14:38:15.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Vanilla Plants Expanded - Succulents/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Vanilla Plants Expanded - Succulents</name>
        <id>2198652536</id>
        <packageId>vanillaexpanded.vplantsesucculents</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>Arlechin</nickname>
            <steamId>76561198162359187</steamId>
        </li>
    </authors>
    <sourceTranslationId>3207802982</sourceTranslationId>
    <lastUpdate>2024-03-31T13:27:53.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/3145590348 Ancient mining industry/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Ancient mining industry</name>
        <id>3141472661</id>
        <packageId>xmb.ancientminingindustry.mo</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>tyulen</nickname>
            <steamId>76561198374567982</steamId>
        </li>
    </authors>
    <sourceTranslationId>3145590348</sourceTranslationId>
    <lastUpdate>2024-04-12T09:07:03.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Death Rattle UA[1.4]/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Death Rattle</name>
        <id>2879582925</id>
        <packageId>trojan.deathrattle</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>tyulen</nickname>
            <steamId>76561198374567982</steamId>
        </li>
    </authors>
    <sourceTranslationId>3051623903</sourceTranslationId>
    <lastUpdate>2024-04-12T09:07:25.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Vanilla Storytellers Expanded - Neron Neolithic/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Vanilla Storytellers Expanded - Neron Neolithic</name>
        <id>2455898908</id>
        <packageId>vse.neronneolithic</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>Arlechin</nickname>
            <steamId>76561198162359187</steamId>
        </li>
    </authors>
    <sourceTranslationId>3180536518</sourceTranslationId>
    <lastUpdate>2024-03-12T14:55:35.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Vanilla Apparel Expanded/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Vanilla Apparel Expanded</name>
        <id>1814987817</id>
        <packageId>VanillaExpanded.VAPPE</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>Arlechin</nickname>
            <steamId>76561198162359187</steamId>
        </li>
    </authors>
    <sourceTranslationId>3125127122</sourceTranslationId>
    <lastUpdate>2023-12-28T19:26:16.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/3076395292 HPT Casino/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Hospitality: Casino</name>
        <id>2939292644</id>
        <packageId>adamas.hospitalitycasino</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>tyulen</nickname>
            <steamId>76561198374567982</steamId>
        </li>
    </authors>
    <sourceTranslationId>3076395292</sourceTranslationId>
    <lastUpdate>2024-04-12T09:10:37.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/More Faction Interaction/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Inadequado4192/UkrainianPlease/master/Translations/Scheme.xsd">
    <originalMod>
        <name>More Faction Interaction</name>
        <id>2379076640</id>
        <packageId>mlie.morefactioninteraction</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>AntiJaoi</nickname>
            <steamId>76561198066973088</steamId>
        </li>
    </authors>
    <sourceTranslationId>2944975214</sourceTranslationId>
    <lastUpdate>2023-04-02T08:08:50.000Z</lastUpdate>
</TranslationDetails>
