=== Inadequado4192/UkrainianPlease/Translations/Scheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="TranslationDetails">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="originalMod">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="id" type="xs:string" />
                            <xs:element name="packageId" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="authors">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="li" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nickname" type="xs:string" />
                                        <xs:element name="steamId" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <!-- Додаємо опціональний елемент SourceTranslationId -->
                <xs:element name="sourceTranslationId" type="xs:string" minOccurs="0" />

                <xs:element name="lastUpdate" type="xs:dateTime" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Vanilla Storytellers Expanded - RimWorld Rick/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Vanilla Storytellers Expanded - RimWorld Rick</name>
        <id>2787762549</id>
        <packageId>vanillaexpanded.storytellers.rick</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>Arlechin</nickname>
            <steamId>76561198162359187</steamId>
        </li>
    </authors>
    <sourceTranslationId>3180553862</sourceTranslationId>
    <lastUpdate>2024-03-12T15:06:21.000Z</lastUpdate>
</TranslationDetails>

=== Inadequado4192/UkrainianPlease/Translations/Completed/Vanilla Social Interactions Expanded/About.xml
<?xml version="1.0" encoding="utf-8"?>
<TranslationDetails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Scheme.xsd">
    <originalMod>
        <name>Vanilla Social Interactions Expanded</name>
        <id>2439736083</id>
        <packageId>vanillaexpanded.vanillasocialinteractionsexpanded</packageId>
    </originalMod>
    <authors>
        <li>
            <nickname>Arlechin</nickname>
            <steamId>76561198162359187</steamId>
        </li>
    </authors>
    <sourceTranslationId>3116756631</sourceTranslationId>
    <lastUpdate>2024-01-08T05:21:59.000Z</lastUpdate>
</TranslationDetails>
